# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="litelocker"
version="${version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="${homepage}"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png"
credits=""
authors="${authors}"
# Description text for the mod (multi line!)
description='''
${description}
'''

[[dependencies.litelocker]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="SERVER"

[[dependencies.litelocker]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${forge_mc_version_range}"
    side="SERVER"
