# Project
rootProject.group=de.veraimt.litelocker

# Minecraft
minecraft_version=1.20.6

# Fabric Properties
# check these on https://fabricmc.net/develop
# yarn_mappings=1.20.6+build.1 #unused, using Mojang mappings
loader_version=0.15.10
#Fabric API
# api_version=0.97.8+1.20.6 #unused

# Mod options
# MAJOR(HUGE changes).MINOR(adding/removing/changing Feature).PATCH(Bug fixes)
mod_version=3.0.0
mod_name=LiteLocker
mod_id=litelocker

# Other

description=A server-sided Minecraft Mod to lock Storage Containers

authors=Veraimt
license=GPL-3.0
homepage=https://github.com/Veraimt/LiteLocker/
sources=https://github.com/Veraimt/LiteLocker/
issues=https://github.com/Veraimt/LiteLocker/issues/

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false